language: ruby
rvm:
- 2.2.2
sudo: false
cache: bundler
before_script:
- cp config/database.travis.yml config/database.yml
- psql -c 'create database hpi_swt2_test;' -U postgres
script:
- bundle exec rake db:test:prepare
- xvfb-run bundle exec rspec spec/
deploy:
  provider: heroku
  api_key:
    secure: AlD8OcLJ2bYi0rJdd44kQnqLvFPv0Flx+gIYORY5jXnA/Q5yjLjkjVE7tP+qOsTY0nMV54Sxxh1mg4YZY9NEe7GVkSMak1Ymmv9b+Y6Z8Nmu0BAtB8gOCwh5/gQ+5EIVuv/wybYMpjbj1YsJL76Z7lZOo7O8iq3KMGxsMC0Q8yJtpimYAErpfEp/FzA+ewi+cG2VwwPOi1S98m0W4KsrMq/5OZZFHvn8qtf+OcGj0MGZz0RO3IkRjE/lTpAi7KqkzgXHX4e+WrTonudpvmuhJHMR9K+TudFZkjbGC2GPlhmG5ip3iIgiNhKnGLsHhIaxGrkedI9uC/YvwT4my2qFcVGz4DR+KcO9QFFG+UCST/c8ekJT3i1eRoLDOK7l/2gzkxdr1LtN8mM8vMMVE8Jhy3JhrSRXHxa8se6w7nSMY1FjnpA0RWh1BWtW+ny8hlkv9Zs4s7l48QALn+3uc6/IQndGeHzkJQ3iIKjwe0Md9rFSDUtIas0mUGfQNrJQykGkb858Xj0hi4ZrxXyaLcr0dQMOcYOfynt/1aYYces4N8h6Aa+B1bA2Iv+OmebP8vnhlyMrnFBZgcmw3awx70/XlD74M0SmqJ7g01AFIJMD1ta3pxRyKV0QOz8eocKDTmjdYrzYSECWuRgY7gDZ7+VWJUGUfkXCodAZL02aEWV9I2M=
  app:
    production: workshopportal
    dev: workshopportal-dev
  on:
    repo: hpi-schuelerklub/workshop-portal
  run:
  - rake db:schema:load
  - rake db:seed
  - rake db:populate_sample_data
  - restart
